services:
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
    restart: always
    working_dir: /app
    volumes:
      - .:/app
      - root_node_modules:/app/node_modules
      - frontend_node_modules:/app/frontend/node_modules
    command: sh -c "npm install && npm run dev -w frontend"

  backend:
    build: ./backend
    ports:
      - '8000:8000'
    restart: always
    working_dir: /app
    environment:
      DATABASE_URL: 'mysql://user:user@db:3306/cais'
      FRONTEND_URL: 'http://localhost:5173'
    volumes:
      - .:/app
      - root_node_modules_backend:/app/node_modules
      - backend_node_modules:/app/backend/node_modules
    command: sh -c "npm install && npm run prisma:generate -w backend && npm run start -w backend"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cais
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

volumes:
  db_data:
  root_node_modules:
  frontend_node_modules:
  root_node_modules_backend:
  backend_node_modules:
