packages:
  - frontend
  - backend
  - shared
autoInstallPeers: true
strictPeerDependencies: false
saveExact: true
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  unrs-resolver: true
