export const CIE10_DATA = [
  { codigo: 'A00', descripcion: 'Cólera' },
  { codigo: 'A01', descripcion: 'Fiebres tifoidea y paratifoidea' },
  {
    codigo: 'A09',
    descripcion: 'Diarrea y gastroenteritis de presunto origen infeccioso',
  },
  { codigo: 'A15', descripcion: 'Tuberculosis respiratoria' },
  { codigo: 'A36', descripcion: 'Difteria' },
  { codigo: 'A37', descripcion: 'Tos ferina' },
  { codigo: 'A50', descripcion: 'Sífilis congénita' },
  { codigo: 'A90', descripcion: 'Dengue' },
  { codigo: 'B01', descripcion: 'Varicela' },
  { codigo: 'B02', descripcion: 'Zóster (herpes zóster)' },
  { codigo: 'B05', descripcion: 'Sarampión' },
  { codigo: 'B06', descripcion: 'Rubéola' },
  { codigo: 'B15', descripcion: 'Hepatitis aguda tipo A' },
  { codigo: 'B16', descripcion: 'Hepatitis aguda tipo B' },
  { codigo: 'B19', descripcion: 'Hepatitis viral, sin otra especificación' },
  { codigo: 'B34', descripcion: 'Infección viral de sitio no especificado' },
  { codigo: 'C18', descripcion: 'Tumor maligno del colon' },
  { codigo: 'C34', descripcion: 'Tumor maligno de los bronquios y del pulmón' },
  { codigo: 'C50', descripcion: 'Tumor maligno de la mama' },
  { codigo: 'C61', descripcion: 'Tumor maligno de la próstata' },
  { codigo: 'D50', descripcion: 'Anemia por deficiencia de hierro' },
  { codigo: 'D64', descripcion: 'Otras anemias' },
  { codigo: 'E03', descripcion: 'Hipotiroidismo' },
  { codigo: 'E05', descripcion: 'Tirotoxicosis (hipertiroidismo)' },
  {
    codigo: 'E10',
    descripcion: 'Diabetes mellitus insulinodependiente (tipo 1)',
  },
  {
    codigo: 'E11',
    descripcion: 'Diabetes mellitus no insulinodependiente (tipo 2)',
  },
  { codigo: 'E66', descripcion: 'Obesidad' },
  {
    codigo: 'E78',
    descripcion:
      'Trastornos del metabolismo de las lipoproteínas (dislipidemia)',
  },
  {
    codigo: 'F10',
    descripcion: 'Trastornos mentales debidos al uso del alcohol',
  },
  { codigo: 'F20', descripcion: 'Esquizofrenia' },
  { codigo: 'F32', descripcion: 'Episodio depresivo' },
  { codigo: 'F40', descripcion: 'Trastornos fóbicos de ansiedad' },
  { codigo: 'F41', descripcion: 'Otros trastornos de ansiedad' },
  { codigo: 'G20', descripcion: 'Enfermedad de Parkinson' },
  { codigo: 'G30', descripcion: 'Enfermedad de Alzheimer' },
  { codigo: 'G35', descripcion: 'Esclerosis múltiple' },
  { codigo: 'G40', descripcion: 'Epilepsia' },
  { codigo: 'G43', descripcion: 'Migraña' },
  { codigo: 'H10', descripcion: 'Conjuntivitis' },
  { codigo: 'H25', descripcion: 'Catarata senil' },
  { codigo: 'H35', descripcion: 'Otros trastornos de la retina' },
  { codigo: 'I10', descripcion: 'Hipertensión esencial (primaria)' },
  { codigo: 'I20', descripcion: 'Angina de pecho' },
  { codigo: 'I21', descripcion: 'Infarto agudo de miocardio' },
  { codigo: 'I25', descripcion: 'Enfermedad isquémica crónica del corazón' },
  { codigo: 'I48', descripcion: 'Fibrilación y aleteo auricular' },
  { codigo: 'I50', descripcion: 'Insuficiencia cardíaca' },
  { codigo: 'I63', descripcion: 'Infarto cerebral' },
  { codigo: 'J00', descripcion: 'Rinofaringitis aguda (resfriado común)' },
  { codigo: 'J03', descripcion: 'Amigdalitis aguda' },
  {
    codigo: 'J06',
    descripcion: 'Infecciones agudas vías respiratorias superiores',
  },
  { codigo: 'J18', descripcion: 'Neumonía, no especificada' },
  { codigo: 'J45', descripcion: 'Asma' },
  { codigo: 'K21', descripcion: 'Enfermedad de reflujo gastroesofágico' },
  { codigo: 'K25', descripcion: 'Úlcera gástrica' },
  { codigo: 'K29', descripcion: 'Gastritis y duodenitis' },
  { codigo: 'K35', descripcion: 'Apendicitis aguda' },
  { codigo: 'K57', descripcion: 'Enfermedad diverticular del intestino' },
  { codigo: 'K80', descripcion: 'Colelitiasis (cálculos biliares)' },
  { codigo: 'L20', descripcion: 'Dermatitis atópica' },
  { codigo: 'L40', descripcion: 'Psoriasis' },
  { codigo: 'M05', descripcion: 'Artritis reumatoide' },
  { codigo: 'M10', descripcion: 'Gota' },
  { codigo: 'M16', descripcion: 'Coxartrosis (artrosis de cadera)' },
  { codigo: 'M17', descripcion: 'Gonartrosis (artrosis de rodilla)' },
  { codigo: 'M54', descripcion: 'Dorsalgia (dolor de espalda)' },
  { codigo: 'N18', descripcion: 'Enfermedad renal crónica' },
  {
    codigo: 'N20',
    descripcion: 'Cálculo del riñón y del uréter (nefrolitiasis)',
  },
  { codigo: 'N39', descripcion: 'Otros trastornos del sistema urinario' },
  { codigo: 'N40', descripcion: 'Hiperplasia de la próstata' },
  { codigo: 'O10', descripcion: 'Hipertensión preexistente en el embarazo' },
  { codigo: 'O80', descripcion: 'Parto único espontáneo' },
  { codigo: 'R05', descripcion: 'Tos' },
  { codigo: 'R10', descripcion: 'Dolor abdominal y pélvico' },
  {
    codigo: 'R50',
    descripcion: 'Fiebre de otro origen y de origen desconocido',
  },
  { codigo: 'R51', descripcion: 'Cefalea' },
  { codigo: 'R55', descripcion: 'Síncope y colapso' },
  { codigo: 'S00', descripcion: 'Traumatismo superficial de la cabeza' },
  { codigo: 'S72', descripcion: 'Fractura del fémur' },
  {
    codigo: 'T14',
    descripcion: 'Traumatismo de región del cuerpo no especificada',
  },
  { codigo: 'U07', descripcion: 'COVID-19' },
  { codigo: 'Z00', descripcion: 'Examen médico general' },
  { codigo: 'Z13', descripcion: 'Examen de detección de otras enfermedades' },
  { codigo: 'Z30', descripcion: 'Atención para anticoncepción' },
  { codigo: 'Z51', descripcion: 'Otro cuidado médico' },
]
